global:
  scrape_interval: 10s
  evaluation_interval: 10s

storage:
  tsdb:
    out_of_order_time_window: 1m

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
