spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/inventory_db
    username: ${DB_USERNAME:popuser}
    password: ${DB_PASSWORD:poppass}

  kafka:
    bootstrap-servers: kafka:9092

  data:
    redis:
      host: redis
      password: ${REDIS_PASSWORD:redispass}

management:
  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
